# A short introduction on solving equation systems numerically for poromechanics

*[Written by: Maxime Pierre, 2023]* \
\
This series of notebooks aims at giving theoretical background on basic methods for solving linear and especially nonlinear systems of equations, as well as examples of their implementation in `python` with examples in poromechanical constitutive modelling. \
When implementing constitutive models, we are often faced with systems of equations that need to be solved, as many of the problems we are dealing with will be **inverse problems**. An inverse problem amounts to determining the causes to an observed outcome. \
Given a behaviour $f:x \rightarrow f(x)$ and an observed outcome $y$, we deal with the following problem:
$$
\text{Find} \ x \ \lvert \ f(x)=y.
$$
Let us take a very simple first example: consider a 1D bar element in linear elasticity. Its behaviour, linking the stress $\sigma$ with the deformation $\varepsilon$ is:
$$
\sigma = E(\varepsilon-\varepsilon_0) = f(\varepsilon),
$$
with $E$ the Young modulus of the material. Then, if we want to calculate the deformation corresponding to a given stress state $\tilde{\sigma}$, we must solve the inverse problem:
$$
\text{Find} \ \varepsilon \ \lvert \ E(\varepsilon-\varepsilon_0) = \tilde{\sigma}.
$$
Of course, this is a trivial problem since the relationship is linear, and is then easily inversed:
$$
\varepsilon = \varepsilon_0 + \frac{\tilde{\sigma}}{E}.
$$
However, the task may not always be this simple. What if we considered nonlinear elasticity? In the case of simple laws such as power laws, we could still manage it easily, but what about more complex functions, for which the inverse is unknown? We need other numerical tools that we will introduce starting from the next notebook. \
More often than not, we will also be dealing with multiple equations to be solved simultaneously: poromechanical problems are coupled. In order to illustrate this, let us take a simple isotropic porous solid with the usual state equations:
$$
\left\{
\begin{array}{}
\sigma = K\varepsilon -bp, \\
\phi - \phi_0 = b\varepsilon + \frac{p}{N}.
\end{array}
\right.
$$
If we consider a force-controlled, undrained isotropic compression with an incompressible fluid, we have for example:
$$
\left\{
\begin{array}{}
\sigma =-\tilde{\sigma}, \\
\phi = \phi_0.
\end{array}
\right.
$$
Finding the corresponding deformation and pressure requires solving the system:
$$
\left\{
\begin{array}{}
K\varepsilon -bp =-\tilde{\sigma}, \\
b\varepsilon + \frac{p}{N} = 0.
\end{array}
\right.
$$
We have two equations and two unknowns, which means we will find a unique solution unless our system is linked. Solving it seems easy enough: we can just express one unknown as a function of the other from the second equation, then inject it in the first, and voilà! That is indeed a decent way to approach that problem, and in fact close to the *Gauss-Seidel* algorithm which we will talk about in a minute. A useful representation of this problem consists in using matrices and vectors:
$$
\begin{bmatrix}
K & -b \\
b & \frac{1}{N}
\end{bmatrix}
\begin{bmatrix}
\varepsilon \\
p
\end{bmatrix}=
\begin{bmatrix}
-\tilde{\sigma} \\
0
\end{bmatrix},
$$
which is a problem of the usual form:
$$
K\cdot U = F
$$
of unknown $U$. We know an easy way of solving this problem: if we can calculate the inverse of $K$, we have:
$$
U = K^{-1}\cdot F.
$$
Let us take a simple example: $\tilde{\sigma}=1$ MPa, $K=1$ GPa, $b = 0.5$ and $N = 1$ GPa.

In [1]:
import numpy as np

# Solicitation
sig_tilde = 1e6

# Material parameters
K = 1e9
b = 0.5
N = 1e9

K = np.array([[K, -b], [b, 1 / N]])
F = np.array([-sig_tilde, 0])

Now that everything is defined, let us calculate our unknowns:

In [2]:
# Calculating the inverse of K
K_inv = np.linalg.inv(K)
# Getting U
U = np.dot(K_inv, F)
print("The corresponding state is : epsilon = {:.4f}, p = {} Pa.".format(*U))

The corresponding state is : epsilon = -0.0008, p = 400000.0 Pa.


In [3]:
# Checking that KU=F
print("Result of K*U: sigma = {} Pa, phi - phi0 = {}.".format(*np.dot(K, U)))

Result of K*U: sigma = -1000000.0000000001 Pa, phi - phi0 = -5.421010862427522e-20.


## Bonus: a bit of matrix manipulation: Gaussian elimination algorithm

As an exercise to familiarize ourself with basic matrix manipulations in `python`, we can try and implement a simple way of solving linear systems of equations, however large they are, without using a built-in matrix inversion function. \
Gauss elimination consists of 3 basic operations:
- Swap two rows of the matrix,
- Multiply a row by a non-zero scalar,
- Add a multiple of one row to another row.

Say we are trying to solve the following linear system:
$$
\left\{\begin{array}{cl}
2x+y-z &=8, \\
4x+2y+2z &=-11, \\
-2x+y+2z &= -3.
\end{array}\right.
$$
We can build the corresponding *augmented matrix*:
$$
\left[
\begin{array}{ccc|c}
2 & 1 & -1 & 8 \\
4 & 2 & 2 & -11 \\
-2 & 1 & 2 & -3 \\
\end{array}
\right]
$$
The goal is to reduce the left $3\times 3$ part to identity to get the solution in the right part. We will first try to have a $1$ and two $0$ in the first column. \
We will start by making a $1$ in position $(1,1)$: we thus multiply the first row by $1/2$ (second operation):
$$
\left[
\begin{array}{ccc|c}
\color{red}{1} & \frac{1}{2} & -\frac{1}{2} & 4 \\
4 & 2 & 2 & -11 \\
-2 & 1 & 2 & -3 \\
\end{array}
\right]
$$
Then, we eliminate the first column in rows 2 and 3 by adding 3 times and 2 times the first row, respectively:
$$
\left[
\begin{array}{ccc|c}
\color{red}{1} & \frac{1}{2} & -\frac{1}{2} & 4 \\
\color{red}{0} & 0 & 4 & -27 \\
\color{red}{0} & 2 & 1 & 5 \\
\end{array}
\right]
$$
The next step is to get a $1$ in position $(2,2)$. However, we currently have $0$ there, so there is no way we can multiply row $2$ to get $1$ in that position. \
We will then swap it with the first row which has a non-zero value in the second column (here, row $3$):
$$
\left[
\begin{array}{ccc|c}
\color{red}{1} & \frac{1}{2} & -\frac{1}{2} & 4 \\
\color{red}{0} & 2 & 1 & 5 \\
\color{red}{0} & 0 & 4 & -27 \\
\end{array}
\right]
$$
Finally, we multiply the second row by $1/2$, eliminate the column $2$ in the row above, then with row $3$ again multiply by $1/4$ and eliminate other values in column $3$. We end up with:
$$
\left[
\begin{array}{ccc|c}
1 & 0 & 0 & -\frac{37}{16} \\
0 & 1 & 0 & \frac{47}{8} \\
0 & 0 & 1 & -\frac{27}{4} \\
\end{array}
\right]
$$
Let us implement the algorithm for any linear system:

In [4]:
def gauss_elimination(A):
    # Here M is an "augmented" matrix, what matters is the number of rows
    M = (
        A.copy()
    )  # Creating a copy of the original matrix, otherwise it will be modified by the function
    nb_rows = M.shape[0]
    for i in range(nb_rows):
        # Check if our pivot is 0
        if M[i, i] == 0:  # We need to swap rows
            j = i
            while M[j, i] == 0:
                if j >= nb_rows:
                    return None
                else:
                    j += 1
            # Swap rows i and j
            aux_row = M[i, :].copy()
            M[i, :] = M[j, :].copy()
            M[j, :] = aux_row
            print("Swapped rows {} and {}:".format(i, j))
            print(M)
        # Now our pivot is non-zero
        M[i, :] = M[i, :] / M[i, i]
        print("Reduced pivot in row {} to 1:".format(i))
        print(M)
        for k in range(nb_rows):
            if k != i:
                M[k, :] = M[k, :] - M[i, :] * M[k, i]
        print("Eliminated other values in column {}:".format(i))
        print(M)
    return M


# Defining our matrices
K = np.array([[2, 1, -1], [4, 2, 2], [-2, 1, 2]], dtype=float)
F = np.array([8, -11, 3], dtype=float).reshape(3, 1)
A = np.hstack((K, F))

# Checking the algorithm against matrix inversion
M = gauss_elimination(A)
print("Solution from Gauss elimination: X={}".format(M[:, -1]))
sol = np.dot(np.linalg.inv(K), F).reshape(
    3,
)
print("Actual solution: X={}".format(sol))
print("You succeeded!" if np.all(M[:, -1] == sol) else "Check your algorithm!")

Reduced pivot in row 0 to 1:
[[  1.    0.5  -0.5   4. ]
 [  4.    2.    2.  -11. ]
 [ -2.    1.    2.    3. ]]
Eliminated other values in column 0:
[[  1.    0.5  -0.5   4. ]
 [  0.    0.    4.  -27. ]
 [  0.    2.    1.   11. ]]
Swapped rows 1 and 2:
[[  1.    0.5  -0.5   4. ]
 [  0.    2.    1.   11. ]
 [  0.    0.    4.  -27. ]]
Reduced pivot in row 1 to 1:
[[  1.    0.5  -0.5   4. ]
 [  0.    1.    0.5   5.5]
 [  0.    0.    4.  -27. ]]
Eliminated other values in column 1:
[[  1.     0.    -0.75   1.25]
 [  0.     1.     0.5    5.5 ]
 [  0.     0.     4.   -27.  ]]
Reduced pivot in row 2 to 1:
[[ 1.    0.   -0.75  1.25]
 [ 0.    1.    0.5   5.5 ]
 [ 0.    0.    1.   -6.75]]
Eliminated other values in column 2:
[[ 1.      0.      0.     -3.8125]
 [ 0.      1.      0.      8.875 ]
 [ 0.      0.      1.     -6.75  ]]
Solution from Gauss elimination: X=[-3.8125  8.875  -6.75  ]
Actual solution: X=[-3.8125  8.875  -6.75  ]
You succeeded!


Gauss elimination can also be used to invert a matrix: just use the previous, but instead of putting the $F$ vector on the right, put the identity matrix. Then, the right matrix will become the inverse of the initially left matrix:
$$
\left[\begin{array}{c|c}
M & I\\
\end{array}\right]
\rightarrow
\left[\begin{array}{c|c}
I & M^{-1}\\
\end{array}\right]
$$
Can you inverse the following matrix $M$?

In [5]:
M = np.array(
    [
        [4, 0, 2, 2, 3],
        [9, 3, 2, 0, 2],
        [0, 9, 1, 9, 7],
        [1, 1, 9, 4, 8],
        [7, 8, 9, 3, 3],
    ],
    dtype=float,
)

# Make Identity Matrix
I = np.zeros((5, 5))
for i in range(5):
    I[i, i] = 1

M_inv = gauss_elimination(np.hstack((M, I)))[:, 5:]
print("Checking M^-1.M: {}".format(np.dot(M_inv, M)))

Reduced pivot in row 0 to 1:
[[1.   0.   0.5  0.5  0.75 0.25 0.   0.   0.   0.  ]
 [9.   3.   2.   0.   2.   0.   1.   0.   0.   0.  ]
 [0.   9.   1.   9.   7.   0.   0.   1.   0.   0.  ]
 [1.   1.   9.   4.   8.   0.   0.   0.   1.   0.  ]
 [7.   8.   9.   3.   3.   0.   0.   0.   0.   1.  ]]
Eliminated other values in column 0:
[[ 1.    0.    0.5   0.5   0.75  0.25  0.    0.    0.    0.  ]
 [ 0.    3.   -2.5  -4.5  -4.75 -2.25  1.    0.    0.    0.  ]
 [ 0.    9.    1.    9.    7.    0.    0.    1.    0.    0.  ]
 [ 0.    1.    8.5   3.5   7.25 -0.25  0.    0.    1.    0.  ]
 [ 0.    8.    5.5  -0.5  -2.25 -1.75  0.    0.    0.    1.  ]]
Reduced pivot in row 1 to 1:
[[ 1.          0.          0.5         0.5         0.75        0.25
   0.          0.          0.          0.        ]
 [ 0.          1.         -0.83333333 -1.5        -1.58333333 -0.75
   0.33333333  0.          0.          0.        ]
 [ 0.          9.          1.          9.          7.          0.
   0.          1.  